export default {
  ADD_REQUEST: 'ADD_PRODUCT_REQUEST',
  ADD_SUCCESS: 'ADD_PRODUCT_SUCCESS',
  ADD_FAILURE: 'ADD_PRODUCT_FAILURE',
  GET_REQUEST: 'GET_PRODUCTS_REQUEST',
  GET_SUCCESS: 'GET_PRODUCTS_SUCCESS',
  GET_FAILURE: 'GET_PRODUCTS_FAILURE',
};
